name: FunctorCategories
version: "2022.02-02"
license: "GPL-2.0-or-later"
date: 2022-02-13
description: |
    Categories of functors

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh

GAP: ">= 4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2021.11-03"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "MonoidalCategories"
      version: ">= 2020.03.01"
      url: "https://homalg-project.github.io/pkg/MonoidalCategories"
    - name: "Algebroids"
      version: ">= 2022.01-19"
      url: "https://homalg-project.github.io/pkg/Algebroids"
    - name: "RingsForHomalg"
      version: ">= 2020.02.04"
      url: "https://homalg-project.github.io/pkg/RingsForHomalg"
    - name: "LinearAlgebraForCAP"
      version: ">= 2020.01.10"
      url: "https://homalg-project.github.io/pkg/LinearAlgebraForCAP"
    - name: "FreydCategoriesForCAP"
      version: ">= 2019.11.02"
      url: "https://homalg-project.github.io/pkg/FreydCategoriesForCAP"
    - name: "CategoryConstructor"
      version: ">= 2021.06-01"
      url: "https://homalg-project.github.io/pkg/CategoryConstructor"
    - name: "SubcategoriesForCAP"
      version: ">= 2021.12-01"
      url: "https://homalg-project.github.io/pkg/SubcategoriesForCAP"

www: https://homalg-project.github.io/pkg/FunctorCategories
readme: README.md
packageinfo: https://homalg-project.github.io/FunctorCategories/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/FunctorCategories/releases/download/v2022.02-02/FunctorCategories-2022.02-02.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/FunctorCategories/releases/download/v2022.02-02/FunctorCategories-2022.02-02.zip

pdf: https://github.com/homalg-project/FunctorCategories/releases/download/v2022.02-02/FunctorCategories-2022.02-02.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    functors, natural transformations, finitely presented categories, functors into categories, functors into pre-additive categories, functors into additive categories, functors into pre-abelian categories, functors into abelian categories.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BS22</span>]   <b class='BibAuthor'>Barakat, M. and Saleh, K.</b>,
     <i class='BibTitle'>FunctorCategories, Categories of functors,
             Version 2022.02-02</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/FunctorCategories">https://homalg-project.github.io/pkg/FunctorCategories</a></span>.
    </p>
    

bibtex: |
    @misc{ FunctorCategories2022.02-02,
      author =           {Barakat, M. and Saleh, K.},
      title =            {{FunctorCategories}, Categories of functors, {V}ersion
                          2022.02-02},
      month =            {Feb},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/FunctorCategories}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{FunctorCategories}}},
      keywords =         {functors;  natural transformations; finitely presented
                          categories;  functors  into  categories; functors into
                          pre-additive   categories;   functors   into  additive
                          categories;   functors  into  pre-abelian  categories;
                          functors into abelian categories},
      printedkey =       {BS22}
    }

